### ISSUE TITLE
ECR777 is currently unsupported

### ISSUE THREAD

**Issue by alexlarraga1** [epirus-io/epirus-cli#70]
In the generation of a new project ERC777 does not allow to create the new project

`D:/Project_path>epirus new erc777
  ______       _
 |  ____|     (_)
 | |__   _ __  _ _ __ _   _ ___
 |  __| | '_ \| | '__| | | / __|
 | |____| |_) | | |  | |_| \__ \
 |______| .__/|_|_|   \__,_|___/
        | |
        |_|
Please enter the project name [Web3App]:

Please enter the package name for your project [io.epirus]:

Please enter the destination of your project [D:/Project_path]:

Generating ERC777 Kotlin project is currently unsupported
`

**Comment by iikirilov** [comment]
Yes - erc777 is only supported with the `--openapi` flag. This is because the java/kotlin project generators currently do not support solc version 0.6.x
