### ISSUE TITLE
Bug with java wrapper command line last version ?

### ISSUE THREAD

**Issue by mmaryo** [epirus-io/epirus-cli#87]
According to documentation https://docs.web3j.io/smart_contracts/#solidity-smart-contract-wrappers

This command 
`epirus solidity generate -a=MyContracts.abi -o=/src/main/java -p=com.abcd`

Returns 
```
Unknown options: '-a=MyContracts.abi', '-o=/src/main/java', '-p=com.abcd'
epirus [OPTIONS] [COMMAND]
Description:
Run Epirus CLI commands
```

Version 1.3.0

I had used it with version 1.2.4 without problem

**Comment by muratogat** [comment]
I was able to run it by using:

`epirus generate solidity generate --abiFile=MyContracts.abi --outputDir=/src/main/java --package=com.abcd`

But surely it doesn't feel right.

**Comment by raduciobanu22** [comment]
The link to documentation doesn't work either.

**Comment by AlexandrouR** [comment]
Just fixed this the command will be `epirus generate solidity`. I will update the documentation asap to reflect the changes.
