### ISSUE TITLE
Unsupported type encountered: tuple

### ISSUE THREAD

**Issue by adamwhitakerwilson** [epirus-io/epirus-cli#96]
First off, thank you all for creating such an amazing product which has saved my life many times over!

I'm just curious if there is a way to work around this? 

Version: ```Version: 1.4.1
Build timestamp: 2021-02-02 11:20:39.278 UTC```

Command : ```epirus generate solidity --abiFile=MCDResolver.abi --package=abc --outputDir=abcp```
Output: ```Generating abc.MCDResolver ... Unsupported type encountered: tuple```

Cheers!
-Adam

**Comment by kinson603** [comment]
Have your contract use ABIV2? (i.e.: arrays of structs and multiple arrays of structs)
Web3j has this problem before but they have fixed it in the latest release. [https://github.com/web3j/web3j/issues/935](url)
I wonder if Epirus would update as well.

**Comment by adamwhitakerwilson** [comment]
Yeah it uses V2, I'm just wondering if there's a workaround where I can sort of trick it somehow.

**Comment by kinson603** [comment]
I think you can just switch to web3j CLI.
The command is the same and it supports ABIV2 right now.

**Comment by adamwhitakerwilson** [comment]
@kinson603 Thanks, I'll try it tomorrow and let you know!

**Comment by adamwhitakerwilson** [comment]
@kinson603 Thanks a lot. It worked!
